name: Jekyll Site CI

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.5  # or the Ruby version you're using
        bundler-cache: true

    - name: Install Dependencies
      run: bundle install

    - name: Build the site
      run: bundle exec jekyll build --trace

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site
